name: regardless_data_module
description: A Regardless mode service.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.3.0
  responsive_builder: ^0.7.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.2.0
  async: ^2.10.0
  multiple_result: ^5.0.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.1.5
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^18.0.1
  app_tracking_transparency: ^2.0.3
  geolocator: ^13.0.2
  geocoding:
  collection: ^1.17.1
  path_provider: ^2.1.1
  sign_in_with_apple: ^6.1.1
  firebase_dynamic_links: ^6.0.5
  intl: ^0.19.0
  cross_file: ^0.3.4+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^2.0.0
  http: ^1.2.1
  google_api_headers: ^4.3.4
  flutter_google_places_sdk: ^0.3.10

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

