name: regardless_data_module
description: A Regardless mode service.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.3.0
  responsive_builder: ^0.7.0
  fluttertoast: ^9.0.0
  freezed_annotation: ^2.2.0
  async: ^2.10.0
  multiple_result: ^5.0.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0

  cloud_firestore: ^6.0.3
  app_tracking_transparency: ^2.0.3
  geolocator: ^14.0.2
  geocoding:
  collection: ^1.17.1
  path_provider: ^2.1.1
  sign_in_with_apple: ^7.0.1
  intl: ^0.20.2
  cross_file: ^0.3.4+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^2.0.0
  http: ^1.2.1
  google_api_headers: ^4.3.4
  flutter_google_places_sdk: ^0.4.0
  dart_mappable: ^4.2.2
  logger: ^1.3.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0
  image: ^4.5.3
  mobile_device_identifier: ^0.0.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.1
  #stacked_generator: ^1.3.3
  dart_mappable_builder: ^4.2.3
#  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

